{"uid":"4b4757e66a1912dae1a509f688f20b0f","children":[{"name":"Test defects","children":[{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b4f6bc0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Create a new entity","uid":"3021689abb2df483","parentUid":"d14bba4eb32a2521500cf1726e5e9576","status":"broken","time":{"start":1727433157853,"stop":1727433157891,"duration":38},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"d14bba4eb32a2521500cf1726e5e9576"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b462fb0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Delete entity","uid":"cf42bdaebf0d1a3f","parentUid":"43bcb98e9b457b1b6d1b8fc624ba7834","status":"broken","time":{"start":1727433158031,"stop":1727433158033,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"43bcb98e9b457b1b6d1b8fc624ba7834"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b52c7f0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Get a single entity","uid":"4118bd1bcbc67826","parentUid":"4bbdbd94d0c19c3eb2ad30a290ebdbdf","status":"broken","time":{"start":1727433158134,"stop":1727433158136,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"4bbdbd94d0c19c3eb2ad30a290ebdbdf"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b6515a0>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Get a list of entities","uid":"1ddf522904052035","parentUid":"4ca0c480d34e57d5d748539759a3a927","status":"broken","time":{"start":1727433158246,"stop":1727433158248,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"4ca0c480d34e57d5d748539759a3a927"},{"name":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8080): Max retries exceeded with url: /api/create (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f096b4b2470>: Failed to establish a new connection: [Errno 111] Connection refused'))","children":[{"name":"Partially update an entity","uid":"242c6fddc0968709","parentUid":"ad1ef540dc4500410c049b89f46de0e3","status":"broken","time":{"start":1727433158348,"stop":1727433158350,"duration":2},"flaky":false,"newFailed":false,"newPassed":false,"newBroken":false,"retriesCount":0,"retriesStatusChange":false,"parameters":[],"tags":[]}],"uid":"ad1ef540dc4500410c049b89f46de0e3"}],"uid":"bdbf199525818fae7a8651db9eafe741"}],"name":"categories"}